name: app
description: Pokemon Pokedex App By Team B
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State Management
  provider: ^6.0.5
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  equatable:
  #
  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  lottie: ^2.6.0
  bot_toast: ^4.1.3
  cached_network_image: ^3.2.3
  sliding_up_panel: ^2.0.0+1
  shared_preferences: ^2.2.1
  animated_theme_switcher: ^2.0.8
  dio: ^5.3.2
  infinite_scroll_pagination: ^4.0.0
  audioplayers: ^5.1.0
  font_awesome_flutter: ^10.5.0
  audio_video_progress_bar: ^2.0.0
  pinput: ^3.0.1
  animations: ^2.0.8
  intl:
  stop_watch_timer: ^3.0.2
  flutter_screenutil: ^5.9.0
  connectivity_plus: ^5.0.2
  youtube_player_flutter: ^8.1.2
  flutter_dotenv: ^5.1.0
  intl_phone_field: ^3.2.0
  table_calendar: ^3.0.9
  collection: ^1.18.0
  http: ^1.1.2
  flutter_credit_card: ^4.0.1 
  hive: ^2.2.3

dev_dependencies:
  mockito:
  build_runner:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter  

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/bg/
    - assets/images/icons/
    - assets/images/pokemons_types/
    - assets/images/technical_records_types/
    - assets/images/technical_machines_types/
    - assets/images/pokemons_generations/generation_1/
    - assets/images/pokemons_generations/generation_2/
    - assets/images/pokemons_generations/generation_3/
    - assets/images/pokemons_generations/generation_4/
    - assets/images/pokemons_generations/generation_5/
    - assets/images/pokemons_generations/generation_6/
    - assets/images/pokemons_generations/generation_7/
    - assets/images/pokemons_generations/generation_7/
    - assets/images/pokemons_generations/generation_8/
    - assets/lotties/
    - assets/images/pokemons_types/20/water.png

    #env
    - .env

  fonts:
    - family: Circular
      fonts:
        - asset:  assets/fonts/CircularStd-Book.otf
        - asset:  assets/fonts/CircularStd-Black.otf